#!/bin/bash

set -e

if [ -z "$GIT_URL"] ; then
  GIT_URL="https://github.com/noahdesu/ceph.git"
fi

# allow the user to provide their own zlog serc
if [ ! -d /ceph/.git ] ; then
  cd /
  # don't let the user define the commit
  git clone --recursive $GIT_URL
  cd /ceph
  git checkout -b cls_zlog remotes/origin/cls_zlog
fi

if [ ! -e /ceph/src/.libs/libcls_zlog.so.1 ]; then
  cd /ceph
  git clean -fd
  git submodule update --init --recursive
  ./autogen.sh
  ./configure
  cd src

  #don't enable multithread because it builds quickly
  make libcls_zlog.la
  make libcls_zlog_client.la
fi


# install cls_zlog
if [ ! -d /zlog/.git ] ; then
  cd /
  git clone https://github.com/noahdesu/zlog.git
fi

cd /zlog
autoreconf -ivf
mkdir -p /tmp/install/rados
cp /ceph/src/cls/zlog/cls_zlog_client.h /tmp/install/rados
CPPFLAGS=-I/tmp/install LDFLAGS=-L/ceph/src/.libs ./configure
make
